### ISSUE TITLE
Can I use `train.sh' to train the model on multiple GPUs?

### ISSUE THREAD

**Issue by chenzhutian** [maudzung/TTNet-Realtime-for-Table-Tennis-Pytorch#1]
It seems that the `train.sh` only train the model using single GPU.
Many thanks!

**Comment by maudzung** [comment]
Hi Chenzhutian,

The `train.sh` bash shell script is for training the model on a single machine that has multiple GPUs.
During training, you can check the usage of GPUs by executing the below command in a terminal: 

```
nvidia-smi -l 1
```

**Comment by chenzhutian** [comment]
Cool! Thank you very much.
