### ISSUE TITLE
ball detection - output always is (0,615)

### ISSUE THREAD

**Issue by ShallowWill** [maudzung/TTNet-Realtime-for-Table-Tennis-Pytorch#16]
Hi @maudzung 

thanks for the code.

I followed 2.1 to prepare the dataset, 2.3.2 to train the model and 2.3.4 to evaluate the model.

The predicted ball address are the same w.r.t. various input.  I am confused about it, can you please help?

The following is the result I got (copied parts of results):

===================== batch_idx: 128 ================================

Ball Detection -         Global stage:   (x, y) - gt = (109, 66), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (657, 557), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.7071067811865476, is net: 0.0), prediction: (is bounce: 0.3838, is net: 0.2197)
Segmentation -           IoU = 0.9526

===================== batch_idx: 129 ================================

Ball Detection -         Global stage:   (x, y) - gt = (107, 65), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (644, 549), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.9238795325112867, is net: 0.0), prediction: (is bounce: 0.3780, is net: 0.2405)
Segmentation -           IoU = 0.9546
  3%|███                                                                                     | 130/3754 [00:05<02:15, 26.74it/s]
===================== batch_idx: 130 ================================

Ball Detection -         Global stage:   (x, y) - gt = (105, 64), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (631, 540), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 1.0, is net: 0.0), prediction: (is bounce: 0.3824, is net: 0.2243)
Segmentation -           IoU = 0.9520

===================== batch_idx: 131 ================================

Ball Detection -         Global stage:   (x, y) - gt = (103, 63), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (620, 535), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.9238795325112867, is net: 0.0), prediction: (is bounce: 0.3847, is net: 0.2165)
Segmentation -           IoU = 0.9512

===================== batch_idx: 132 ================================

Ball Detection -         Global stage:   (x, y) - gt = (101, 62), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (606, 527), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.7071067811865476, is net: 0.0), prediction: (is bounce: 0.3761, is net: 0.2479)
Segmentation -           IoU = 0.9515

===================== batch_idx: 133 ================================

Ball Detection -         Global stage:   (x, y) - gt = (99, 61), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (595, 522), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.38268343236508984, is net: 0.0), prediction: (is bounce: 0.3805, is net: 0.2310)
Segmentation -           IoU = 0.9516
  4%|███▏                                                                                    | 134/3754 [00:05<02:14, 26.96it/s]
===================== batch_idx: 134 ================================

Ball Detection -         Global stage:   (x, y) - gt = (97, 61), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (583, 516), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.0, is net: 0.0), prediction: (is bounce: 0.3822, is net: 0.2254)
Segmentation -           IoU = 0.9504

===================== batch_idx: 135 ================================

Ball Detection -         Global stage:   (x, y) - gt = (209, 79), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (1255, 669), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.0, is net: 0.0), prediction: (is bounce: 0.1441, is net: 0.3184)
Segmentation -           IoU = 0.9645

===================== batch_idx: 136 ================================

Ball Detection -         Global stage:   (x, y) - gt = (215, 79), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (1290, 667), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.38268343236508984, is net: 0.0), prediction: (is bounce: 0.3759, is net: 0.2237)
Segmentation -           IoU = 0.9632

===================== batch_idx: 137 ================================

Ball Detection -         Global stage:   (x, y) - gt = (220, 78), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (1325, 664), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.7071067811865476, is net: 0.0), prediction: (is bounce: 0.3824, is net: 0.2238)
Segmentation -           IoU = 0.9662
  4%|███▏                                                                                    | 138/3754 [00:05<02:13, 27.01it/s]
===================== batch_idx: 138 ================================

Ball Detection -         Global stage:   (x, y) - gt = (227, 77), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (1366, 658), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 0.9238795325112867, is net: 0.0), prediction: (is bounce: 0.3814, is net: 0.2278)
Segmentation -           IoU = 0.9627

===================== batch_idx: 139 ================================

Ball Detection -         Global stage:   (x, y) - gt = (233, 77), prediction = (0, 73)
Ball Detection -         Local stage:    (x, y) - gt = (-1, -1), prediction = (0, 0)
Ball Detection -         Overall:        (x, y) - org: (1399, 655), prediction = (0, 615)
Event Spotting -         gt = (is bounce: 1.0, is net: 0.0), prediction: (is bounce: 0.3815, is net: 0.2275)
Segmentation -           IoU = 0.9652

**Comment by SHX9610** [comment]
hello，ShallowWill , is this problem solved?

**Comment by ShallowWill** [comment]
still no luck to solve the problem, already gave up

**Comment by egehancosgun** [comment]
Is there any progress now? I also have the same issue.
