### ISSUE TITLE
When training using ``

### ISSUE THREAD

**Issue by chenzhutian** [maudzung/TTNet-Realtime-for-Table-Tennis-Pytorch#2]
When I try to run the training using `train_1st_phase`, it shows that
```
fileNotFoundError: [Errno 2] No such file or directory: '../../dataset/training/images/game_2/img_111667.jpg'
```

Could you please help?

**Comment by maudzung** [comment]
Hi Chenzhutian,

How did you extract images from videos? 
You should execute `python extract_smooth_labellings.py` to extract images when you set an argument `----smooth-labelling` in train bash shell scripts. _(I will update the instruction for data preparation soon)_

**Comment by chenzhutian** [comment]
Hi @maudzung ,

Thank you for your reply.
I use `python extract_selected_images.py` to extract images from the videos.
Now I am running the `extract_all_images.py`, but it is really slow.

**Comment by maudzung** [comment]
You can execute `python extract_all_images.py` to extract all images in videos, but I don't recommend to do that.
To save your time and your resource, you just need to run `python extract_smooth_labellings.py`.
Anw, grab a cup of coffee and have fun coding 👍

**Comment by chenzhutian** [comment]
Awesome. I have stoped and now runing `extract_smooth_labellings.py`.
BTW, may I ask what are the differences between `extract_smooth_labellings.py` and `extract_selected_images.py`?

**Comment by maudzung** [comment]
- `extract_selected_images.py`: Extract images based on events given in the annotation files. For example, if an event occurs at frame _#10_, we need to extract from frame _#6_ to frame _#14_.
- `extract_smooth_labellings.py`: The smooth labeling technique is mentioned in the paper **_(part 5.2)_**. This script is to extract images based on smoothed events.
