### ISSUE TITLE
Not producing comparable results for ball detection and event classification modules. 

### ISSUE THREAD

**Issue by AugustRushG** [maudzung/TTNet-Realtime-for-Table-Tennis-Pytorch#43]
Hi, I'm just wondering has anybody got comparable results with the paper using this code? I have trained it using what is provided but the RMSE is way too large. In their paper, they stated that their RMSE for global is 3.60 and for local is 1.46. But what I got after training RMSE for global is 46.8 and for local is 90.5, there is quite a big margin between.
This happened to the event classification module as well, where the PCE is supposed to be 0.979 and SPCE is 0.975 but I am getting PCE 0.582 and SPCE 0.838.

Also, there is some mismatch between this repo and the paper on the implementation of the ball detection module. In paper 
![image](https://github.com/user-attachments/assets/fc293b9a-4496-46cd-a24a-23552d8d3962)
there are two FC layers after FC2 one produces X and one produces Y. This repo only has one FC which produces a vector with length 448, it is the width+height (320,128). I modified it and got the right result. 

Just wondering has anybody got comparable results with the ball detection module?

**Comment by AugustRushG** [comment]
Hi guys, I have fixed all problems and also modified the training code to produce good results, please refer to [https://github.com/AugustRushG/TTNet-Real-time-Analysis-System-for-Table-Tennis-Pytorch](url).

**Comment by Tencyfy** [comment]
@AugustRushG 您好，请问可以提供预训练的模型吗，我的代码无法达到预期效果，对球的预测结果都是同一个位置

**Comment by Tencyfy** [comment]
@AugustRushG my e-mail is tencyfy@qq.com/Tencyfy@qq.com . Thanks a lot！
